#!/usr/bin/env bash
set -e

# link: https://docs.docker.com/engine/installation/linux/ubuntu/#os-requirements

apt-get update

# install the linux-image-extra-* packages, which allow Docker to use the aufs storage drivers
apt-get install -y \
    linux-image-extra-$(uname -r) \
    linux-image-extra-virtual

# install packages to allow apt to use a repository over HTTPS
apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

# add Docker’s official GPG key and repository
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

# update apt-get with new repository
apt-get update

# install docker
apt-get install -y \
	docker-ce

# run this to make sure that docker is installed correctly
# > sudo docker run hello-world

# allow `vagrant` user to run docker without sudo
# groupadd docker
usermod -aG docker vagrant
